### ISSUE TITLE
Assume port 20408 for GRPC exporter

### ISSUE THREAD

**Issue by aparcar** [labgrid-project/labgrid#1429]
We assume port 20408 already for coordinator and client, however not for the exporter. I suggest we check if the line mentioned below checks for a port, and if it does not exists, add port 20408.

https://github.com/labgrid-project/labgrid/blob/ae0907928feec6b4bbaba7658cf5095d241a848d/labgrid/remote/exporter.py#L1028

**Comment by Emantor** [comment]
~We do, we either get the env variable `LG_COORDINATOR` or fallback to `127.0.0.1:20408`:~
https://github.com/labgrid-project/labgrid/blob/ae0907928feec6b4bbaba7658cf5095d241a848d/labgrid/remote/exporter.py#L989

Ah, only the port argument is inconsistent. I guess @Bastian-Krause fixed this for the client since the client requires the proxy-manager to work, I am not against a fix for the exporter.

**Comment by aparcar** [comment]
I guess this doesn't have a priority, it's just a inconsistency in the setup.
